#!/bin/bash

# A script to get colours from xrdb & deploy it to polybar, termite & rofi.

DIR="$HOME/.config/themes/configs"

getcolors () {
	FOREGROUND="$(xrdb -query | grep 'foreground:'| awk '{print $NF}')"
	BACKGROUND="$(xrdb -query | grep 'background:'| awk '{print $NF}')"
	CURSOR="$(xrdb -query | grep 'cursorColor:'| awk '{print $NF}')"
	BLACK="$(xrdb -query | grep 'color0:'| awk '{print $NF}')"
	RED="$(xrdb -query | grep 'color1:'| awk '{print $NF}')"
	GREEN="$(xrdb -query | grep 'color2:'| awk '{print $NF}')"
	YELLOW="$(xrdb -query | grep 'color3:'| awk '{print $NF}')"
	BLUE="$(xrdb -query | grep 'color4:'| awk '{print $NF}')"
	MAGENTA="$(xrdb -query | grep 'color5:'| awk '{print $NF}')"
	CYAN="$(xrdb -query | grep 'color6:'| awk '{print $NF}')"
	WHITE="$(xrdb -query | grep 'color7:'| awk '{print $NF}')"
	ALTBLACK="$(xrdb -query | grep 'color8:'| awk '{print $NF}')"
	ALTRED="$(xrdb -query | grep 'color9:'| awk '{print $NF}')"
	ALTGREEN="$(xrdb -query | grep 'color10:'| awk '{print $NF}')"
	ALTYELLOW="$(xrdb -query | grep 'color11:'| awk '{print $NF}')"
	ALTBLUE="$(xrdb -query | grep 'color12:'| awk '{print $NF}')"
	ALTMAGENTA="$(xrdb -query | grep 'color13:'| awk '{print $NF}')"
	ALTCYAN="$(xrdb -query | grep 'color14:'| awk '{print $NF}')"
	ALTWHITE="$(xrdb -query | grep 'color15:'| awk '{print $NF}')"
}

bspbar () {
echo "
[color]

foreground = ${FOREGROUND}
background = ${BACKGROUND}
black = ${BLACK}
red = ${RED}
green = ${GREEN}
yellow = ${YELLOW}
blue = ${BLUE}
magenta = ${MAGENTA}
cyan = ${CYAN}
white = ${WHITE}
altblack = ${ALTBLACK}
altred = ${ALTRED}
altgreen = ${ALTGREEN}
altyellow = ${ALTYELLOW}
alblue = ${ALTBLUE}
altmagenta = ${ALTMAGENTA}
altcyan = ${ALTCYAN}
altwhite = ${ALTWHITE}
pink = #EC407A
sep = #3C4449
orange = #E57C46
purple = #BA68C8
lime = #B9C244
" > $DIR/polybar.conf
}

bspterm () {
	echo "
[colors]
foreground=${FOREGROUND}
background=${BACKGROUND}
cursor=${CURSOR}

color0=${BLACK}
color1=${RED}
color2=${GREEN}
color3=${YELLOW}
color4=${BLUE}
color5=${MAGENTA}
color6=${CYAN}
color7=${WHITE}
color8=${ALTBLACK}
color9=${ALTRED}
color10=${ALTGREEN}
color11=${ALTYELLOW}
color12=${ALTBLUE}
color13=${ALTMAGENTA}
color14=${ALTCYAN}
color15=${ALTWHITE}
	" > $DIR/kitty.conf
}

bsprofi () {
	cat > $HOME/.config/themes/configs/rofi.conf <<- EOF	
	* {
		background:			${BACKGROUND};
		foreground:			${FOREGROUND};
		selected:			${BLUE};
		urgent:				${RED};
		on:					${GREEN};
		off:				${RED};
	}
	EOF
}

main () {
	xrdb -load $HOME/.Xresources
	getcolors
	bspbar
	# bspterm
	bsprofi
}

main
