#!/usr/bin/python
import os
import re
from multiprocessing import Pool
from pathlib import Path


# file path
home_address = str(Path.home())
file_content = ""
dir_path = os.path.join(home_address, "Documents",
                        "Experiments")
file_path = os.path.join(dir_path,"test.cfg")


def write_configs(device):
    try:
        global dir_path
        # old_regex = "^![\!\s]*{device}\s*[\n]*((?:\n[^\!]*)+)" 
        regex = rf"^#[#\s]*{device}\s*[\n]*((?:\n[^#]*)+)"
        result_list = re.findall(regex.strip(), file_content, re.MULTILINE)
        result = ' '.join([str(elem) for elem in result_list])
        result = os.linesep.join([s for s in result.splitlines() if s])
        file = os.path.join(dir_path, device+".ini")
        with open(file, 'w') as handler:
            handler.write(result)
        return
    except Exception as error:
        print(error)


def main():
    global file_content, file_path
    try:
        with open(file_path, 'r') as handler:
            file_content = handler.read()
    except Exception as error:
        print(error)
        return

    # get devices name by reading first line
    all_devices = list()
    try:
        infile = open(file_path, 'r')
        first_line = infile.readline()
        first_line = first_line.replace("#", "").strip()
        all_devices = first_line.split(",")

        session_file_contents = '\n'.join([i for i in all_devices[0:]])
        with open(os.path.join(dir_path,"SessionList.txt"),"w") as handler:
            handler.write(session_file_contents)
    except Exception:
        print("Please enter the devices name on first line of your master config file")
        return

    # get the contents of each device into a separate file
    p = Pool(len(all_devices))
    p.map(write_configs, all_devices)
    p.close()
    p.join()


if __name__ == "__main__":
    main()
