#!/usr/bin/bash
DIR="$HOME/.config/i3"
FILE="$DIR/config"

cat $DIR/main_config > $FILE \
	&& cat $DIR/keybindings >> $FILE \
	&& cat $DIR/startup >> $FILE \
	&& cat $DIR/stick_to_workspace >> $FILE \
	&& cat $DIR/programs_properties >> $FILE \
	&& echo "Merged Successfully" && i3-msg reload > /dev/null 2>&1 ;exit 1

echo "Failed to merge"

	
