#!/bin/bash

DIR="$HOME/.config/bspwm"

rofi_command="rofi -theme $DIR/rofi/themes/powermenu.rasi"

# Options
screen=""
area=""
window=""

# Variable passed to rofi
options="$screen\n$area\n$window"

chosen="$(echo -e "$options" | $rofi_command -p 'Screenshot' -dmenu -selected-row 1)"
case $chosen in
    $screen)
        sleep 1;scrot '%d-%m-%Y_%H.%M.%S_$wx$h.png' -e 'mv $f ~/Pictures/screenshots/'
        ;;
    $area)
        sleep 1;scrot -s '%d-%m-%Y_%H.%M.%S_$wx$h.png' -e 'mv $f ~/Pictures/screenshots/'
        ;;
    $window)
        sleep 1;scrot -u '%d-%m-%Y_%H.%M.%S.png' -e 'mv $f ~/Pictures/screenshots/'
        ;;
esac

