#! /bin/sh

pgrep -x polybar > /dev/null || /home/saad/.config/polybar/default/launch.sh &

source $HOME/.config/bspwm/startup

source $HOME/.config/bspwm/rules

bspc monitor -d I II III IV V VI VII VIII IX X

# bspc config border_width         2
# bspc config window_gap          12

# bspc config border_radius 5
# bspc config split_ratio          0.50



